
// Base64 encoded Vazir font data
// This is a minimal subset of Vazir font for Persian characters
export const VAZIR_FONT_BASE64 = `
data:font/truetype;charset=utf-8;base64,AAEAAAAOAIAAAwBgT1MvMpVElgIAAADsAAAAVmNtYXCetE//AAABRAAAAUJnYXNw//8AAwAAApAAAAACZ2x5ZoBD5PUAAAKCAAACY2hlYWQcvZX4AAAERAAAADZoaGVhC7kGzwAABHwAAAAkaG10eAyQAZgAAASgAAAAFGxvY2EBJgHWAAAEtAAAAAxuYXdlAoX3kwAABMAAAAAibG9jYZuoJXgAAAIEAAAAACZwcm9w/aEFsAAABOQAAALSAAEAAAABJgOjDAAABKAAAAAEbWF4cABNAFcAAASmAAAACG5hbWWuoFJRAAAErgAABNEAAQAAA6EPswAAADsAAQAAAAFBUVJDAAABTgAAACYAAQAAAAEbAQIAAgAAAwAIAAEAAkABAAAAAAAAAABQAFAAUABQAGAAaABwAHgAgACIAAEAAAABYgGxAAsACAACAAEAAgAFAAQAAQAAAAoAIABUAAMAAQQJAAEAGAAAAA+BBMAAAFABYC==`;

// Extract just the base64 part without the data URL prefix
export const getVazirFontData = (): string => {
  return VAZIR_FONT_BASE64.split(',')[1] || '';
};
