// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsuyosbvebpzcfdhtnjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzdXlvc2J2ZWJwemNmZGh0bmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTEyMjAsImV4cCI6MjA2NjY2NzIyMH0.ffCllJ9rnIliLkiEg4I90URH3BNTlxGrlJLCqxrunmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);