// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxylosusnzyrrinsodqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4eWxvc3Vzbnp5cnJpbnNvZHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDMzODQsImV4cCI6MjA2NjUxOTM4NH0.yyRcignhIa48W7S7RTcC8pgAIdA7woDF7bAOscC-Uwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);